/* Progressive, dependency-free beam UI. All figures use the solved beam arrays. */
(() => {
  'use strict';
  const B=BeamLearningEngine, $=s=>document.querySelector(s), host=$('#foundations');
  const f=(x,n=3)=>Number(x).toFixed(n), max=a=>Math.max(...a.map(Math.abs),1e-12);
  const st={length:450,width:20,height:10,E:2000,density:1.24,support:'cantilever',elements:30,loads:[{kind:'point',position:450,force:2}]};
  let result=null, mode=0, animated=false, phase=0;
  const style=document.createElement('style'); style.textContent=`
    #foundations{max-width:1450px;margin:auto;padding:22px;font-size:16px;line-height:1.55}
    #foundations h1{font-size:32px;margin:4px 0} #foundations h2{font-size:23px} #foundations h3{font-size:18px}
    .pathway{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}.pathway button{padding:10px;background:var(--panel);border:1px solid var(--line);border-radius:8px;cursor:pointer}
    .pathway button[aria-pressed=true]{border:2px solid var(--accent)}
    .foundation-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.5fr);gap:20px;align-items:start}.foundation-grid>*{min-width:0}
    .foundation-card{background:var(--panel);border:1px solid var(--line);padding:20px;border-radius:12px;margin-bottom:16px}
    #foundations input,#foundations select{padding:7px;background:var(--bg);border:1px solid var(--line);border-radius:5px;width:100%}
    .beam-fields{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px}.beam-fields label{font-size:14px;display:block;min-width:0}.beam-fields input,.beam-fields select{min-width:0}
    #foundations svg{width:100%;height:auto;background:#f5f8fb;border-radius:8px} #foundations summary{cursor:pointer;font-weight:600}
    .beam-equation{font-family:Georgia,serif;text-align:center;background:var(--panel-2);padding:14px;font-size:20px;border-radius:8px;margin:12px 0}
    .beam-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.beam-kpis div{padding:12px;background:var(--panel-2);border-radius:8px}.beam-kpis b{display:block;font-size:20px}
    #beamCharts{display:grid;grid-template-columns:1fr 1fr;gap:10px} #foundations table{width:100%;font-size:14px} #foundations th,#foundations td{text-align:left;padding:7px;border-bottom:1px solid var(--line)}
    .beam-chart{margin:0;min-width:0}.beam-chart figcaption{min-height:48px;font-size:14px}.support-notice{border:2px solid var(--warn);padding:14px;margin:10px 0;background:var(--panel-2)}
    @media(max-width:900px){.foundation-grid{grid-template-columns:minmax(0,1fr)}#beamCharts{grid-template-columns:minmax(0,1fr)}.beam-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:560px){#foundations{padding:10px}.foundation-card{padding:12px}.beam-fields{grid-template-columns:minmax(0,1fr)}#foundations h1{font-size:26px}}
  `;document.head.append(style);
  host.innerHTML=`<header><p>MIE 446 · Aerospace Structures</p><h1>From a beam to your printed wing</h1><p>Predict → apply a load → solve → explain. Start with one support condition, then add complexity.</p></header>
    <nav class="pathway" aria-label="Learning pathway"><button data-stage="cantilever" aria-pressed="true">1 · Cantilever beam</button><button data-stage="fixed-fixed" aria-pressed="false">2 · Fixed–fixed beam</button><button data-stage="simply-supported" aria-pressed="false">3 · Simply supported</button><button data-stage="shell" aria-pressed="false">4 · Wing skin only</button><button data-stage="rods" aria-pressed="false">5 · Add rods / reinforcement</button><button data-stage="ribs" aria-pressed="false">6 · Add ribs</button><button data-stage="project" aria-pressed="false">7 · Course modular wing</button></nav>
    <div class="foundation-grid"><div><article class="foundation-card" id="beamTheory"></article>
    <section class="foundation-card"><h2>Define your beam</h2><form id="beamGeometry"><div class="beam-fields">${[['length','Length L','mm',450],['width','Width b','mm',20],['height','Depth h','mm',10],['E','Elastic modulus E','MPa',2000],['density','Density','g/cm³',1.24],['elements','Requested elements','',30]].map(([id,name,unit,val])=>`<label>${name} (${unit})<input name="${id}" type="number" step="any" value="${val}" required></label>`).join('')}</div><button class="btn primary" type="submit" style="margin-top:12px">Apply beam dimensions</button></form><p>Changing span clears incompatible loads to a 2 N tip load. No self-weight unless you add it as a line load.</p></section>
    <section class="foundation-card"><h2>Apply loads</h2><p>Beam sign convention: <b>positive load and displacement are downward</b>. Negative values point upward. q is force per length (N/mm), not pressure.</p>
    <form id="beamLoadForm"><div class="beam-fields"><label>Load shape<select id="beamLoadKind"><option value="point">Point force</option><option value="rectangle">Rectangular / uniform</option><option value="triangle">Triangular (zero at start)</option><option value="trapezoid">Trapezoidal</option></select></label><label>Point station or distributed start (mm)<input id="beamLoadA" type="number" step="any" value="225" required></label><label>Distributed end (mm)<input id="beamLoadB" type="number" step="any" value="450"></label><label>Point force P (N)<input id="beamP" type="number" step="any" value="2"></label><label>q at start (N/mm)<input id="beamQ0" type="number" step="any" value="0.004"></label><label>q at end (N/mm)<input id="beamQ1" type="number" step="any" value="0.008"></label></div><button class="btn" type="submit" style="margin-top:12px">Add this load</button></form>
    <div id="beamLoads"></div><button class="btn" id="beamClear">Clear all loads</button> <button class="btn" id="beamCentre">Centre point · 2 N</button><p>Changing supports preserves your loads. A force applied directly at a restrained end can be carried by that support without bending the span. Use the centre-point preset to compare all three support conditions.</p>
    <h3>Compare shapes at the same total force</h3><p>These presets replace all loads with a full-span load of 2 N. An equal area under q(x) does not mean an equal bending moment.</p><div class="lesson-actions"><button class="btn" data-shape="uniform">Uniform · 2 N</button><button class="btn" data-shape="root">Root-heavy triangle · 2 N</button><button class="btn" data-shape="tip">Tip-heavy triangle · 2 N</button></div>
    <p id="beamStatus" role="status"></p></section></div>
    <div><section class="foundation-card"><h2>Free body and calculated deformation</h2><div id="beamPicture"></div><p>Grey: undeformed beam. Blue: exaggerated deflection. Purple: applied forces. Green: ideal supports. Read numerical displacement, not the drawing's height.</p><div id="beamKpis" class="beam-kpis"></div><div id="beamReactions"></div></section>
    <section class="foundation-card"><h2>Follow the calculation</h2><p>Loads + supports → reactions → shear V and moment M → curvature → displacement and stress.</p><div id="beamCharts"></div><label>Probe position x (mm)<input id="beamProbe" type="range" min="0" max="450" step="1" value="0"></label><div id="beamProbeRead"></div></section>
    <section class="foundation-card"><h2>Modes: a pattern, not a forced response</h2><p>A natural mode is an undamped vibration pattern. Its amplitude is normalized, so this animation is <b>not</b> the displacement caused by your static load. Frequency is computed from stiffness and mass; playback is slowed for visibility.</p><div id="beamModeButtons" class="lesson-actions"></div><button class="btn" id="beamAnimate">Animate mode</button><div id="beamModePicture" style="margin-top:10px"></div><p>These are bending modes only. Higher modes develop additional changes in direction. Natural frequency alone does not predict resonance amplitude, damping, flutter or failure.</p></section>
    <section class="foundation-card"><h2>Verify before trusting</h2><button class="btn" id="beamRefine">Compare 10 / 20 / 40 elements</button><div id="beamConvergence"></div><p>For a constant-EI beam, some simple cases are represented exactly by a small number of cubic elements. A tiny change with refinement is not proof that the real clamp or printed material is modelled correctly.</p><label>My explanation<textarea id="beamExplain" rows="3" style="width:100%" placeholder="The largest stress is at … because …; the largest displacement is at …"></textarea></label><button class="btn" id="beamDownload">Download study record</button></section></div></div>
    <section class="foundation-card"><h2>What equations are actually solved?</h2><div class="beam-equation">A = bh &nbsp; · &nbsp; I = bh³/12 &nbsp; · &nbsp; EI v⁗ = q<br>M = −EI v″ &nbsp; · &nbsp; V = dM/dx &nbsp; · &nbsp; dV/dx = −q<br>σ<sub>x</sub> = −Mz/I &nbsp; · &nbsp; τ<sub>max</sub> = 3|V|/(2A)<br>K u = f &nbsp; · &nbsp; K φ = ω² M φ &nbsp; · &nbsp; f<sub>n</sub> = ω/(2π)</div>
    <p>x is distance along the beam, z is measured upward from its neutral axis, v is downward displacement, E is modulus, I is second moment of area, and κ = v″ is curvature with this sign convention. Positive M is sagging: top compression, bottom tension. The beam FE uses displacement and slope at each node, cubic interpolation, consistent distributed loads and a mass matrix. K and M in the eigenvalue equation are matrices, not the bending moment.</p><p>τ<sub>max</sub> is the neutral-axis shear stress in a solid rectangle, <b>not surface shear</b>. The top/bottom surfaces have zero transverse shear in this idealization. The plots show nominal beam stress; they do not resolve clamp edges, contact, holes, plasticity or buckling. The wing workspace uses upward-positive loading and states that convention explicitly.</p>
    <p><a href="https://teachbooks.tudelft.nl/computational-modelling/structural_linear/euler_bernouilli.html" target="_blank" rel="noopener">TU Delft: Euler–Bernoulli finite elements</a> · <a href="https://help.solidworks.com/2026/english/simtutorialonline/Creating_Beam_Diagrams.htm" target="_blank" rel="noopener">SOLIDWORKS: beam diagrams</a> · <a href="https://help.solidworks.com/2025/english/SolidWorks/cworks/HIDD_Mode_Shape_Amplitude.htm" target="_blank" rel="noopener">Mode amplitude interpretation</a></p><p>This app follows an educational simulation workflow; it is not SOLIDWORKS and does not replace solid/shell contact, nonlinear or fracture analysis.</p></section>`;
  const svg=(title,body,h=240)=>`<svg viewBox="0 0 760 ${h}" role="img" aria-label="${title}"><style>text{font:16px Arial;fill:#19354b}</style><text x="24" y="27" font-weight="bold">${title}</text>${body}</svg>`;
  let chartData=[];
  function chart(title,ys,unit,color='#246fba') {
    const index=chartData.push({ys,unit,title})-1,L=st.length,scale=max(ys),X=x=>100+610*x/L,Y=v=>125-70*v/scale;
    const grid=[-1,-.5,0,.5,1].map(t=>`<path d="M100 ${Y(t*scale)}H710" stroke="#c5d1db"/><text x="88" y="${Y(t*scale)+5}" text-anchor="end">${f(t*scale,2)}</text>`).join('');
    const ticks=[0,.25,.5,.75,1].map(t=>`<text x="${X(t*L)}" y="224" text-anchor="middle">${f(t*L,0)}</text>`).join('');
    return `<figure class="beam-chart" data-beam-chart="${index}">${svg(title+' ('+unit+')',grid+`<polyline points="${result.x.map((x,i)=>X(x)+','+Y(ys[i])).join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>`+ticks+'<text x="360" y="252">Span position x (mm)</text>',270)}<figcaption>Hover or touch the plot for sampled values; the position slider below also works.</figcaption></figure>`;
  }
  function theory() {
    const fixed=st.support==='fixed-fixed',simple=st.support==='simply-supported';
    $('#beamTheory').innerHTML=`<h2>${fixed?'2 · Fixed at both ends':simple?'3 · Simply supported':'1 · One fixed end, one free end'}</h2><p>${fixed?'Both end displacement and slope are zero. End moments and forces share the load. Equilibrium alone is insufficient: the deformation must also satisfy both clamps.':simple?'Vertical motion is restrained at both ends but rotation is free. A pin and roller carry vertical reactions without applied end couples.':'The root cannot translate or rotate. The free end can move and turn. The clamp must carry both a reaction force and a reaction moment.'}</p><div class="beam-equation">${fixed?'v(0) = v(L) = 0<br>v′(0) = v′(L) = 0':simple?'v(0) = v(L) = 0<br>M(0) = M(L) = 0':'v(0) = v′(0) = 0<br>Free end: no end moment unless applied'}</div><p><b>Zero displacement is not zero stress.</b> In a uniform cantilever with a tip force, |M| and nominal bending stress are largest at the clamp; displacement is largest at the tip. In a fixed–fixed beam, end moments can be nonzero even though both ends do not move.</p><details><summary>Hand-check benchmarks</summary><p>Use P for a point force and q for a constant line load.</p><div class="beam-equation">${fixed?'Centre P: δ<sub>mid</sub> = PL³/(192EI)<br>Uniform q: δ<sub>mid</sub> = qL⁴/(384EI)':simple?'Centre P: δ<sub>mid</sub> = PL³/(48EI)<br>Uniform q: δ<sub>mid</sub> = 5qL⁴/(384EI)':'Tip P: δ<sub>tip</sub> = PL³/(3EI)<br>Uniform q: δ<sub>tip</sub> = qL⁴/(8EI)'}</div><p>These apply only to the named ideal beam/load case. Do not apply a tip-force formula to an arbitrary interior force or a trapezoidal load.</p></details>`;
  }
  function picture(){
    const X=x=>55+650*x/st.length;let d='<path d="M55 151H705" stroke="#afbfca" stroke-width="12"/>';
    const support=x=>st.support==='simply-supported'?`<path d="M${x} 158l-13 22h26Z" fill="#168957"/>`:`<path d="M${x} 125v55" stroke="#168957" stroke-width="12"/>`;
    d+=support(55);if(st.support!=='cantilever')d+=support(705);
    const arrow=(x,q,len)=>`<path d="M${x} ${q>=0?150-len:150+len}V150l-5 ${q>=0?-9:9}m5 ${q>=0?9:-9}l5 ${q>=0?-9:9}" fill="none" stroke="#ad368b" stroke-width="2.5"/>`;
    st.loads.forEach(p=>{if(p.kind==='point')d+=arrow(X(p.position),p.force,65)+`<text x="${Math.min(X(p.position)-20,635)}" y="55">${p.force} N</text>`;else{const qmax=Math.max(Math.abs(p.qStart),Math.abs(p.qEnd),1e-9);for(let k=0;k<=8;k++){const q=p.qStart+(p.qEnd-p.qStart)*k/8;if(Math.abs(q)>1e-12)d+=arrow(X(p.start+(p.end-p.start)*k/8),q,48*Math.abs(q)/qmax);}d+=`<text x="${X(p.start)}" y="85">q: ${f(p.qStart,4)} → ${f(p.qEnd,4)} N/mm</text>`;}});
    const amp=max(result.deflection);d+=`<polyline points="${result.x.map((x,i)=>`${X(x)},${151+45*result.deflection[i]/amp}`).join(' ')}" fill="none" stroke="#246fba" stroke-width="3"/><text x="55" y="233">x = 0</text><text x="625" y="233">L = ${st.length} mm</text>`;
    $('#beamPicture').innerHTML=svg('Your loads and ideal supports',d,250);
  }
  function probe(){const x=+$('#beamProbe').value;let i=0;while(i<result.x.length-1&&result.x[i+1]<=x)i++;$('#beamProbeRead').innerHTML=`<p>Nearest sampled x = ${f(result.x[i],2)} mm: V = ${f(result.shear[i])} N; M = ${f(result.moment[i])} N·mm; v = ${f(result.deflection[i],4)} mm; σ<sub>top</sub> = ${f(result.stressTop[i])} MPa; σ<sub>bottom</sub> = ${f(result.stressBottom[i])} MPa.</p>`;}
  function renderMode(){if(!result)return;const m=result.modes[mode];$('#beamModePicture').innerHTML=svg(`Bending mode ${mode+1} · ${f(m.frequencyHz,2)} Hz · normalized`, `<path d="M55 130H705" stroke="#aebbc8" stroke-dasharray="6 5"/><polyline points="${m.x.map((x,i)=>`${55+650*x/st.length},${130+65*m.shape[i]*(animated?Math.sin(phase):1)}`).join(' ')}" fill="none" stroke="#246fba" stroke-width="4"/><text x="55" y="225">Display amplitude is arbitrary; animation is slowed, not real time.</text>`);}
  function render(){
    theory();picture();probe();renderMode();
    const supported=st.loads.length>0&&st.loads.every(p=>p.kind==='point'&&Math.abs(p.force)>0&&(p.position===0||(st.support!=='cantilever'&&p.position===st.length)));
    if(supported){$('#beamTheory').insertAdjacentHTML('afterbegin','<div class="support-notice" role="status"><b>Your loads act directly on restrained ends.</b><p>Zero span deflection here is expected: the supports take the forces. No load was moved automatically.</p><button class="btn primary" id="beamMoveCentre">Move these point loads to midspan</button></div>');$('#beamMoveCentre').onclick=()=>attempt(()=>{st.loads=st.loads.map(p=>({...p,position:st.length/2}));});}
    chartData=[];
    $('#beamKpis').innerHTML=[['Maximum |v|',f(result.maxima.deflection,4)+' mm'],['Maximum |σ|',f(result.maxima.bendingStress)+' MPa'],['Total applied force',f(result.resultant)+' N']].map(([n,v])=>`<div>${n}<b>${v}</b></div>`).join('');
    $('#beamReactions').innerHTML=`<h3>Support reactions</h3><table><tr><th>Station</th><th>Force (+down)</th><th>Moment (+clockwise)</th></tr>${result.reactions.map(r=>`<tr><td>${r.x} mm</td><td>${f(r.force)} N</td><td>${f(r.moment)} N·mm</td></tr>`).join('')}</table><p>ΣF residual = ${result.equilibrium.force.toExponential(2)} N; ΣM residual = ${result.equilibrium.moment.toExponential(2)} N·mm.</p>`;
    $('#beamCharts').innerHTML=chart('Shear V',result.shear,'N')+chart('Bending moment M',result.moment,'N·mm')+chart('Displacement v (positive down)',result.deflection,'mm')+chart('Top-fibre stress σ (tension +)',result.stressTop,'MPa')+chart('Bottom-fibre stress σ',result.stressBottom,'MPa')+chart('Maximum rectangular shear |τ|',result.shearStressMax,'MPa');
    $('#beamLoads').innerHTML=`<ol>${st.loads.map((p,i)=>`<li>${p.kind==='point'?`${p.force} N at x=${p.position} mm`:`${p.qStart} → ${p.qEnd} N/mm over ${p.start}–${p.end} mm`} <button class="btn" data-delete-load="${i}">Remove load ${i+1}</button></li>`).join('')}</ol>`;
    $('#beamLoads').querySelectorAll('[data-delete-load]').forEach(b=>b.onclick=()=>attempt(()=>{st.loads.splice(+b.dataset.deleteLoad,1);}));
    $('#beamCharts').querySelectorAll('[data-beam-chart]').forEach(el=>{el.onpointermove=e=>{const box=el.querySelector('svg').getBoundingClientRect(),x=Math.max(0,Math.min(st.length,((e.clientX-box.left)/box.width*760-100)/610*st.length));let i=0;while(i<result.x.length-1&&result.x[i+1]<=x)i++;const d=chartData[+el.dataset.beamChart];el.querySelector('figcaption').textContent=d.title+': x='+f(result.x[i],2)+' mm; '+f(d.ys[i],5)+' '+d.unit+' (sample; at a jump use the span slider for the right-side value).';};});
    $('#beamModeButtons').innerHTML=result.modes.map((m,i)=>`<button class="btn" data-beam-mode="${i}" aria-pressed="${i===mode}">Mode ${i+1}: ${f(m.frequencyHz,2)} Hz</button>`).join('');
    $('#beamModeButtons').querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=+b.dataset.beamMode;render();});
    $('#beamStatus').textContent=result.warnings.length?result.warnings.join(' '):'Solved. Predict the next change before editing.';
  }
  function attempt(edit){const old=JSON.parse(JSON.stringify(st));try{edit();result=B.solve(st);$('#beamProbe').max=st.length;$('#beamProbe').value=Math.min(+$('#beamProbe').value,st.length);render();$('#beamConvergence').innerHTML='';}catch(e){Object.assign(st,old);$('#beamStatus').textContent=e.message;}}
  $('#beamGeometry').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);attempt(()=>{const previous=st.length;for(const k of ['length','width','height','E','density','elements'])st[k]=+fd.get(k);if(previous!==st.length){st.loads=[{kind:'point',position:st.length,force:2}];$('#beamLoadB').value=st.length;}});};
  $('#beamLoadForm').onsubmit=e=>{e.preventDefault();attempt(()=>{const k=$('#beamLoadKind').value,a=+$('#beamLoadA').value,b=+$('#beamLoadB').value,q0=+$('#beamQ0').value,q1=+$('#beamQ1').value;if(st.loads.length>=12)throw Error('Use at most 12 loads.');st.loads.push(k==='point'?{kind:'point',position:a,force:+$('#beamP').value}:{kind:'distributed',start:a,end:b,qStart:k==='triangle'?0:q0,qEnd:k==='rectangle'?q0:q1});});};
  $('#beamClear').onclick=()=>attempt(()=>{st.loads=[];});
  $('#beamCentre').onclick=()=>attempt(()=>{st.loads=[{kind:'point',position:st.length/2,force:2}];});
  host.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>attempt(()=>{const k=b.dataset.shape,q=2/st.length;st.loads=[{kind:'distributed',start:0,end:st.length,qStart:k==='tip'?0:k==='root'?2*q:q,qEnd:k==='root'?0:k==='tip'?2*q:q}];}));
  host.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{const s=b.dataset.stage;if(['cantilever','fixed-fixed','simply-supported'].includes(s)){attempt(()=>{st.support=s;});host.querySelectorAll('[data-stage]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}else if(document.documentElement.dataset.wingReady==='true'){window.dispatchEvent(new CustomEvent('wing-learning-stage',{detail:s}));}else{const msg=$('#beamStatus');msg.textContent='The 3-D workspace is not ready. It needs WebGL and an internet connection to load its graphics libraries. Reload when connected; the beam lessons still work.';msg.scrollIntoView({block:'center'});}});
  $('#beamProbe').oninput=probe;
  $('#beamAnimate').onclick=()=>{animated=!animated;$('#beamAnimate').textContent=animated?'Pause mode':'Animate mode';renderMode();};
  setInterval(()=>{if(animated&&!host.hidden&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){phase+=.18;renderMode();}},80);
  $('#beamRefine').onclick=()=>{try{$('#beamConvergence').innerHTML='<table><tr><th>Requested elements</th><th>Max |v| (mm)</th><th>f₁ (Hz)</th></tr>'+[10,20,40].map(elements=>{const r=B.solve({...st,elements});return `<tr><td>${elements} (+ load-boundary nodes)</td><td>${f(r.maxima.deflection,6)}</td><td>${f(r.modes[0].frequencyHz,4)}</td></tr>`;}).join('')+'</table>';}catch(e){$('#beamStatus').textContent=e.message;}};
  $('#beamDownload').onclick=()=>{const blob=new Blob([JSON.stringify({input:st,explanation:$('#beamExplain').value,reactions:result.reactions,maxima:result.maxima,equilibrium:result.equilibrium,modes:result.modes.map(m=>({frequencyHz:m.frequencyHz})),assumptions:result.assumptions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MIE446-beam-study.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  attempt(()=>{});
})();
