// Inlined inside the Wing Lab UI closure; uses its current solved R and controls.
const localStudy={pressure:120};
let observationDraft={rows:'',frequency:'',source:'measured',notes:''};
function renderTeachingPanels() {
  const g=R.geometry, stations=[0,...R.ribs,g.semiSpan];
  const bay=Math.max(...stations.slice(1).map((s,i)=>s-stations[i]));
  $('#localModels').innerHTML=`<h2>Local skin bending: compare assumptions before numbers</h2>
    <p>Both examples are <b>flat, isotropic, linear-elastic teaching models</b>, separate from global wing bending. They omit curvature, membrane action, print anisotropy, joints and buckling. Neither is the actual wing's local displacement solution. Default b is the root skin arc width, not a verified distance between simple supports.</p>
    <div class="learn-layout"><div>${svgFrame('A · One-way strip', '<path d="M90 120H575" stroke="#376782" stroke-width="8"/><path d="M90 125l-15 25h30ZM575 125l-15 25h30Z" fill="#21824c"/><text x="90" y="80">Uniform pressure ↓ ↓ ↓ ↓</text><text x="160" y="180">Only the two ends support bending</text><text x="195" y="225">Span a between ribs</text>')}<p>Independent narrow strips span a. Their sides provide no support. δ ∝ a⁴, so halving a divides this model's δ by 16.</p></div>
    <div>${svgFrame('B · Two-way rectangular plate', '<rect x="170" y="65" width="330" height="140" fill="#dfeaf2" stroke="#21824c" stroke-width="8"/><text x="220" y="135">Uniform pressure ↓</text><text x="280" y="240">Span a</text><text x="520" y="135">Width b</text>')}<p>All four green edges are assumed simply supported: w = 0, normal bending moment = 0; rotation is free. Those supports must exist for this model to apply. Shorter span action limits growth when a/b is large.</p></div></div>
    <div class="equation">Strip: δ = 5pa⁴/(32Et³), σ = 3pa²/(4t²)<br>Plate: D = Et³/[12(1−ν²)], D∇⁴w = p<br>w = Σ W<sub>mn</sub> sin(mπx/a) sin(nπy/b)<br>W<sub>mn</sub> = 16p / {π⁶Dmn[(m/a)²+(n/b)²]²}, m,n odd<br>M<sub>x</sub> = −D(w<sub>,xx</sub>+νw<sub>,yy</sub>), σ<sub>x,surface</sub> = ±6M<sub>x</sub>/t²</div>
    <form id="localForm" class="beam-fields"><label>Uniform pressure (Pa)<input id="stripPressure" type="number" min="0" step="any" value="${localStudy.pressure}" required></label><label>Rib bay a (mm)<input id="stripBay" type="number" min="1" step="any" value="${nf(bay,2)}" required></label><label>Assumed supported width b (mm)<input id="plateWidth" type="number" min="1" step="any" value="${nf(R.props.skinWidth[0],2)}" required></label><button class="btn" id="stripSolve" type="submit">Compare strip and plate</button></form><div id="stripResult"></div>
    <p>We use δ/t ≤ 0.2 as a conservative classroom warning threshold, not a design standard. Passing it does not validate the boundary conditions. A result above it is only a linear extrapolation. Do not add these numbers to global wing displacement. The change near a/b ≈ 1 explains two-way action, <b>not a rule that rib spacing must equal chord</b>.</p>
    <p><a href="https://www.ramsay-maunder.co.uk/downloads/The-Navier-Solution-for-the-SSSS-Plate.pdf" target="_blank" rel="noopener">Navier series and convergence</a></p>`;
  const updateLocal=()=>{
    try {
      const p={a:+$('#stripBay').value,b:+$('#plateWidth').value,t:g.skin,E:R.pla.E,nu:R.pla.nu,pressure:+$('#stripPressure').value};localStudy.pressure=p.pressure;
      const full=TeachingModels.panel(p),half=TeachingModels.panel({...p,a:p.a/2}),fine=TeachingModels.panel({...p,terms:101});
      const rows=[['Strip',p.a,full.strip],['Strip',p.a/2,half.strip],['Plate',p.a,full.plate],['Plate',p.a/2,half.plate]];
      const curve=Array.from({length:40},(_,i)=>{const ratio=.25+i*3.75/39;return [ratio,TeachingModels.panel({...p,a:ratio*p.b}).plate.w];});
      const ymax=Math.max(...curve.map(a=>a[1]),1e-12);
      const drawing=`<path d="M80 55V225H630" fill="none" stroke="#668399"/><path d="M190 55V225" stroke="#b6530b" stroke-dasharray="5 4"/><polyline points="${curve.map(([x,y])=>`${80+550*(x-.25)/3.75},${225-155*y/ymax}`).join(' ')}" fill="none" stroke="#246fa0" stroke-width="3"/><text x="90" y="65">δ up to ${nf(ymax,3)} mm</text><text x="85" y="252">a/b = 0.25</text><text x="180" y="252">1</text><text x="590" y="252">4</text>`;
      $('#stripResult').innerHTML=`<div class="tablewrap"><table><tr><th>Model</th><th>a (mm)</th><th>Linear δ (mm)</th><th>δ/t</th><th>Centre |σa| / |σb| (MPa)</th><th>Validity warning</th></tr>${rows.map(([name,a,r])=>`<tr><td>${name}</td><td>${nf(a,2)}</td><td>${nf(r.w,4)}${r.ratio>.2?' †':''}</td><td>${nf(r.ratio,2)}</td><td>${nf(r.sigmaA,3)} / ${r.sigmaB==null?'not modelled':nf(r.sigmaB,3)}</td><td>${r.status}</td></tr>`).join('')}</table></div><p><b>† Linear extrapolation—not a valid real-wing deflection.</b> t=${g.skin} mm, E=${R.pla.E} MPa, ν=${R.pla.nu}. ${full.thin?'Thin-plate aspect screen passed.':'Thin-plate assumption questionable: short side/thickness < 20.'}</p><p>Plate centre δ, series upper indices 61 → 101: ${nf(full.plate.w,6)} → ${nf(fine.plate.w,6)} mm. Numerical convergence does not validate the physical model.</p>${svgFrame('Plate response versus aspect ratio (b fixed)',drawing)}<p>Halving a: strip δ ratio ${nf(full.strip.w?half.strip.w/full.strip.w:0,4)}; plate δ ratio ${nf(full.plate.w?half.plate.w/full.plate.w:0,4)}. Ratios are not defined at zero pressure (displayed as 0).</p>`;
    }catch(e){$('#stripResult').textContent=e.message;}
  };
  $('#localForm').onsubmit=e=>{e.preventDefault();updateLocal();};updateLocal();
  renderBucklingModels();renderTorsionLab();renderRibChange();renderObservations();
}
function renderBucklingModels() {
  const b=TeachingModels.buckling(R);
  $('#bucklingModels').innerHTML=`<h2>Buckling: two comparisons, no combined wing allowable</h2><p>U = compressive demand × safety factor / assumed critical stress. These are different idealizations, <b>not two checks with interchangeable capacities</b>.</p><div class="tablewrap"><table><tr><th>Idealization</th><th>Maximum U</th><th>What it assumes</th></tr><tr><td>Flat panel between ribs</td><td>${nf(b.flat,3)}</td><td>Simply supported rectangular plate; no curvature benefit.</td></tr><tr><td>Equivalent circular cylinder</td><td>${nf(b.cylinder,3)}</td><td>Idealized radius and cylinder knockdown; not a validated airfoil-panel boundary condition.</td></tr></table></div><p>The legacy solver selects max(plate capacity, cylinder capacity), which can mask rib-spacing changes when the cylinder estimate dominates. That result is retained only in the engine for reproducible reference comparisons; <b>it is excluded from student governing/pass summaries</b>. Neither U above certifies the printed skin. Stability remains unresolved without an applicable curved-panel/local-shell model and material/imperfection evidence.</p><p>Other-check U and these comparison U values have different scopes. Low material stress does not establish buckling safety. <a href="https://ntrs.nasa.gov/citations/20205011530" target="_blank" rel="noopener">NASA SP-8007 concerns circular cylinders</a>, not arbitrary airfoil shells.</p>`;
}
function renderTorsionLab() {
  const g=R.geometry,z=TeachingModels.zeroTipTwist(R,E), X=y=>55+570*y/g.semiSpan,Z=x=>65+135*x/g.rootChord;
  const path=Array.from(R.y,(y,i)=>`${X(y)},${Z(R.props.xsc[i])}`).join(' ');
  $('#torsionLab').innerHTML=`<h2>Find zero tip twist—not just the local shear centre</h2><p>For a straight uniform prism, a transverse force through its shear centre produces no torsion in this uncoupled model. In the tapered model x<sub>sc</sub> varies with y. A fixed tip-force line can lie ahead of one section's shear centre and behind another's. Opposite contributions may cancel at the tip while intermediate sections still rotate.</p><div class="equation">T(y) = P[x<sub>sc</sub>(y)−x<sub>P</sub>]<br>φ<sub>tip</sub> = ∫T/GJ dy + ΣT<sub>seam</sub>/k<sub>torsion</sub><br>x<sub>P,zero</sub> = [∫x<sub>sc</sub>/GJ dy + Σx<sub>sc,seam</sub>/k] / [∫1/GJ dy + Σ1/k]</div>
    ${svgFrame('Plan view: local shear-centre path',`<path d="M55 65H625V${Z(g.tipChord)}L55 ${Z(g.rootChord)}Z" fill="#dfeaf2" stroke="#46667d"/><polyline points="${path}" fill="none" stroke="#168957" stroke-width="4"/><path d="M55 ${Z(z.x)}H625" stroke="#b6530b" stroke-dasharray="6 4"/><text x="70" y="245">Green: xsc(y) · dashed: zero-tip-twist force line</text>`)}
    <p>Root xsc=${nf(R.props.xsc[0],2)} mm; last sampled xsc=${nf(R.props.xsc.at(-1),2)} mm. This model predicts a zero-tip-twist tip-load fraction of <b>${nf(z.fraction,4)}c</b>, with x measured from the aligned leading edge. It is a result of this reduced tapered-beam idealization, not a certified loading point for the real wing.</p>
    <p>Predict the sign first. Each button replaces current loads with a 2 N upward tip force; geometry and material stay unchanged.</p><div class="lesson-actions"><button class="btn" data-twist-f="0.25">Test 0.25c</button><button class="btn" data-twist-f="0.30">Test 0.30c</button><button class="btn" data-twist-f="${z.fraction}" ${z.fraction<0||z.fraction>1?'disabled':''}>Test predicted zero</button></div><p>Current study: ${wingLoadName(R)}. Tip twist ${nf(R.twist.at(-1)*180/Math.PI,6)}°; largest |twist| along span ${nf(Math.max(...R.twist.map(Math.abs))*180/Math.PI,6)}°. A near-zero tip value does not imply zero torsion everywhere.</p>`;
  $('#torsionLab').querySelectorAll('[data-twist-f]').forEach(b=>b.onclick=()=>{if(running||stale)return;S.load={...S.load,kind:'tip',tipForce:2,tipFraction:+b.dataset.twistF};changed();});
}
function renderRibChange() {
  $('#ribChange').innerHTML=`<h2>What did the ribs change?</h2><p>Compare this study to the same geometry with all editable interior ribs removed. Rods, skins, joints and the prescribed load stay the same; interface ribs remain. With flight inertia relief, changing mass also changes net structural loading. With a fixed tip force, global EI/GJ and deflection should remain unchanged in this model.</p><button class="btn" id="compareNoRibs">Compute controlled rib comparison</button><div id="ribDelta"></div>`;
  $('#compareNoRibs').onclick=async()=>{if(running||stale)return;const baseR=R,button=$('#compareNoRibs');button.disabled=true;$('#ribDelta').textContent='Computing comparison…';await frame();try {
    const other=TeachingModels.studentResult(E.solve({...engineInput(),geometry:{...R.geometry,customInteriorRibs:[]}}));
    if(R!==baseR)return;
    const metrics=r=>[r.ribs.length,r.mass.printed,Math.max(...[0,...r.ribs,r.geometry.semiSpan].slice(1).map((v,i)=>v-[0,...r.ribs,r.geometry.semiSpan][i])),r.props.EI[0],r.deflection.at(-1),r.fem.fBending[0]];
    const a=metrics(other),b=metrics(R),names=['Rib count','Printed mass (g)','Longest support bay (mm)','Root EI (N·mm²)','Tip deflection (mm)','First bending frequency (Hz)'];
    $('#ribDelta').innerHTML=`<div class="tablewrap"><table><tr><th>Quantity</th><th>No editable interior ribs</th><th>Current</th><th>Change</th></tr>${names.map((n,i)=>`<tr><td>${n}</td><td>${nf(a[i],3)}</td><td>${nf(b[i],3)}</td><td>${nf(b[i]-a[i],3)}</td></tr>`).join('')}</table></div><p>Rib mass and skin-bay support change. Distributed section EI/GJ do not include rib diaphragm stiffness; a similar beam deflection is not evidence ribs are unnecessary. Compare the separate local-panel models and unresolved buckling assumptions above.</p>`;
  }catch(e){$('#ribDelta').textContent=e.message;}finally{button.disabled=false;}};
}
function renderObservations() {
  $('#observations').innerHTML=`<h2>Optional: model → observation → judgement</h2><p>No laboratory is required for this lesson. If measured data become available, enter 3–100 rows as <b>force N, displacement mm</b>, using matching signs. Fit includes an intercept for displacement zero-offset. The model comparison requires the same tip-load location, assembly, material, restraint and linear range. A real load-cell/accelerometer is not connected by this page.</p><form id="observationForm"><label>Source<select id="observationSource"><option value="measured">Measured data supplied by me</option><option value="synthetic">Synthetic demonstration—not an experiment</option></select></label><label>Force, displacement pairs<textarea id="observationRows" rows="5" placeholder="0, 0.02&#10;1, 1.12&#10;2, 2.22"></textarea></label><label>First measured bending frequency (Hz, optional)<input id="observationFrequency" type="number" min="0" step="any"></label><label>Fixture, uncertainty and limitations<textarea id="observationNotes" rows="3"></textarea></label><div class="lesson-actions"><button class="btn" type="submit">Fit and compare</button><button class="btn" type="button" id="syntheticObservations">Load clearly labelled synthetic example</button></div></form><div id="observationResult"></div><p>Agreement does not establish fracture, fatigue, nonlinear contact, buckling or flight safety. Data stay in this page; they are not uploaded.</p>`;
  for(const [key,id] of Object.entries({rows:'observationRows',frequency:'observationFrequency',source:'observationSource',notes:'observationNotes'}))$('#'+id).value=observationDraft[key];
  const save=()=>{observationDraft={rows:$('#observationRows').value,frequency:$('#observationFrequency').value,source:$('#observationSource').value,notes:$('#observationNotes').value};};
  $('#observationForm').oninput=save;
  $('#syntheticObservations').onclick=()=>{$('#observationSource').value='synthetic';$('#observationRows').value='0, 0.02\n1, 1.12\n2, 2.22\n3, 3.32';$('#observationFrequency').value='20';$('#observationNotes').value='Invented linear data for demonstrating the fit; not physical measurements.';save();};
  $('#observationForm').onsubmit=e=>{e.preventDefault();save();try{const rows=observationDraft.rows.trim().split(/\n/).map(s=>s.split(/[,;\s]+/).filter(Boolean).map(Number)),f=TeachingModels.fitObservations(rows);const freq=observationDraft.frequency.trim()===''?null:Number(observationDraft.frequency);if(freq!==null&&(!Number.isFinite(freq)||freq<=0))throw Error('Frequency must be positive or empty.');$('#observationResult').innerHTML=`<p><b>${observationDraft.source==='synthetic'?'SYNTHETIC DEMONSTRATION — not experimental validation':'User-supplied measurements — not independently verified'}</b></p><p>δ = ${nf(f.offset,4)} + ${nf(f.compliance,4)}P; R²=${nf(f.r2,5)}; stiffness=${nf(f.stiffness,4)} N/mm. Unit-tip model stiffness=${nf(R.stiffness.tip,4)} N/mm; difference=${nf(100*(f.stiffness/R.stiffness.tip-1),2)}%. This model stiffness is bending-only and excludes clearance dead band; compare only matching measurements.</p>${freq===null?'':`<p>Entered first bending frequency=${nf(freq,3)} Hz; model=${nf(R.fem.fBending[0],3)} Hz; difference=${nf(100*(freq/R.fem.fBending[0]-1),2)}%.</p>`}`;}catch(e){$('#observationResult').textContent=e.message;}};
}
