import assert from "node:assert/strict";
import { createRequire } from "node:module";
const E = createRequire(import.meta.url)("./engine.js");
const base = E.makeGeometry();
const defaultStations = [112.5, 146, 154, 225, 296, 304, 337.5];
assert.deepEqual(E.ribStations(base), defaultStations);
const stations = [56.3, 112.5, 225, 337.5, 393.7];
const custom = E.makeGeometry({ customInteriorRibs: stations });
assert.equal(E.ribStations(custom).length, 9);
assert.deepEqual(E.ribStations(E.makeGeometry({ customInteriorRibs: [] })), [146, 154, 296, 304]);
assert.deepEqual(E.ribStations(E.makeGeometry({ modules: 1, customInteriorRibs: [] })), []);
for (const ys of [[0], [450], [1], [150], [146], [155], [112.5, 113], [NaN], [Infinity], ["100"], Array(17).fill(10)])
  assert.throws(() => E.makeGeometry({ customInteriorRibs: ys }));
for (const n of [-1, 1.5, 17, NaN]) assert.throws(() => E.makeGeometry({ interiorRibs: n }));
assert.throws(() => E.makeGeometry({ customInteriorRibs: [20, 22], ribThickness: 2.5 }));
assert.ok(Object.isFrozen(custom.customInteriorRibs));
assert.notEqual(custom.customInteriorRibs, stations);
const tip = { kind: "tip", tipForce: 2, tipFraction: .3 };
const a = E.solve({ geometry: base, load: tip });
const b = E.solve({ geometry: custom, load: tip });
const close = (x, y, abs = 1e-5) => assert.ok(Math.abs(x - y) < abs, `${x} != ${y}`);
assert.ok(b.mass.printed > a.mass.printed);
close(a.V[0], 2); close(b.V[0], 2);
close(a.M[0], 900); close(b.M[0], 900);
// New stations slightly change quadrature and the beam mesh, not physical EI/GJ.
close(a.deflection.at(-1), b.deflection.at(-1), .001);
close(a.twist.at(-1), b.twist.at(-1), 1e-5);
a.sections.forEach((s, i) => { close(s.EIf, b.sections[i].EIf); close(s.GJ, b.sections[i].GJ); });
assert.ok(b.fem.fBending[0] < a.fem.fBending[0]);
const maxBay = r => { const s = [0, ...r.ribs, r.geometry.semiSpan]; return Math.max(...s.slice(1).map((y, i) => y - s[i])); };
assert.ok(maxBay(b) < maxBay(a));
const flight = { kind: "flight", inertiaRelief: true, aircraftMass: 1, loadFactor: 2, distribution: "uniform" };
const f0 = E.solve({ geometry: base, load: flight });
const f1 = E.solve({ geometry: custom, load: flight });
close(f0.liftN, f1.liftN);
close(f0.V[0] - f1.V[0], (f1.mass.printed - f0.mass.printed) * 2 * 9.81 / 1000, 1e-5);
const thinner = E.solve({ geometry: { ...base, skin: 1.0 }, load: tip });
assert.ok(thinner.mass.printed < a.mass.printed);
assert.ok(thinner.deflection.at(-1) > a.deflection.at(-1));
console.log("PASS: custom ribs, locked interfaces, bounds/overlap validation, mass, fixed-load equilibrium, unchanged EI/GJ, modal mass, support bays, flight inertia relief, and skin-thickness response.");
console.log(JSON.stringify({ baseline: { ribs: a.ribs.length, mass: a.mass.printed, bay: maxBay(a), deflection: a.deflection.at(-1) }, modified: { ribs: b.ribs.length, mass: b.mass.printed, bay: maxBay(b), deflection: b.deflection.at(-1) } }));
