// DOM component tests, not a WebGL/browser visual test.
// Install jsdom separately; optionally set MIE446_JSDOM_MODULE to its module path.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const require=createRequire(import.meta.url);
const {JSDOM}=require(process.env.MIE446_JSDOM_MODULE || 'jsdom');
const read=f=>readFileSync(new URL(f,import.meta.url),'utf8');
const dom=new JSDOM('<div id="foundations"></div>',{runScripts:'outside-only'});
const w=dom.window, ctx=dom.getInternalVMContext();
w.matchMedia=()=>({matches:true});
w.HTMLElement.prototype.scrollIntoView=function(){};
w.setInterval=()=>0;
vm.runInContext(read('./beam_learning_engine.js'),ctx);
vm.runInContext(read('./foundations_ui.js'),ctx);
const $=s=>w.document.querySelector(s), click=s=>$(s).click();
const kpi=()=>$('#beamKpis').textContent;
assert.match(kpi(),/18\.2250 mm/);
click('#beamCentre');
click('[data-stage="fixed-fixed"]');
assert.match(kpi(),/0\.2848 mm/);
assert.match($('#beamTheory').textContent,/Both end displacement and slope are zero/);
click('[data-stage="simply-supported"]');
assert.match(kpi(),/1\.1391 mm/);
click('[data-shape="uniform"]');
assert.match(kpi(),/0\.7119 mm/);
click('#beamRefine');
assert.match($('#beamConvergence').textContent,/40/);
click('#beamClear');
assert.match(kpi(),/0\.0000 mm/);
$('#beamLoadKind').value='trapezoid';$('#beamLoadA').value='0';$('#beamLoadB').value='450';
$('#beamQ0').value='.002';$('#beamQ1').value='.006';
$('#beamLoadForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.match(kpi(),/1\.800 N/);
click('[data-stage="shell"]');
assert.match($('#beamStatus').textContent,/not ready/);
w.document.documentElement.dataset.wingReady='true';
let requested='';w.addEventListener('wing-learning-stage',e=>requested=e.detail);
click('[data-stage="shell"]');assert.equal(requested,'shell');
assert.ok(!/NaN|undefined|Infinity/.test($('#foundations').innerHTML));
dom.window.close();

// Render the actual member/load lesson functions with real engine results.
const E=require('./engine.js'), source=read('./wing_lab_template.html');
const wingDOM=new JSDOM('<div id="app" data-lesson-stage="project"></div><div id="memberLesson"></div><div id="wingLoadLesson"></div>',{runScripts:'outside-only'});
const c=wingDOM.getInternalVMContext();
c.E=E;c.nf=(x,d=2)=>Number(x).toFixed(d);c.R=E.solve({});
c.S={geometry:c.R.geometry,load:c.R.load,stressComponent:'skin'};
c.running=false;c.stale=false;
c.$=s=>wingDOM.window.document.querySelector(s);
c.setPlot=p=>{c.lastPlot=p;};c.applyXray=()=>{};c.setAnatomy=p=>{c.lastAnatomy=p;};
c.changed=()=>{c.changeCount=(c.changeCount||0)+1;};c.flash=s=>{throw Error(s);};
c.engineInput=()=>({geometry:c.S.geometry,load:c.S.load});
vm.runInContext(source.slice(source.indexOf('  function svgFrame('),source.indexOf('  function renderDesignLab(')),c);
c.renderMemberLesson();
assert.match(c.$('#memberLesson').textContent,/3 interior/);
assert.match(c.$('#memberLesson').textContent,/full stress map inside every rib is not solved/);
assert.match(c.$('#memberLesson').textContent,/146.0 mm/);
c.$('#rodStress').click();assert.equal(c.S.stressComponent,'rods');assert.equal(c.lastPlot,'stress');
c.$('#ribBearingView').click();assert.equal(c.lastAnatomy,'ribs');
const rows=[...c.$('#stripResult').querySelectorAll('tr')].slice(1).map(tr=>[...tr.cells].map(td=>parseFloat(td.textContent)));
assert.ok(Math.abs(rows[0][1]/rows[1][1]-4)<.02);
assert.ok(Math.abs(rows[0][2]/rows[1][2]-16)<.02);
c.renderWingLoads();
c.$('#wingKind').value='trapezoid';c.$('#wingA').value='40';c.$('#wingB').value='400';
c.$('#wingLoadForm').dispatchEvent(new wingDOM.window.Event('submit',{bubbles:true,cancelable:true}));
assert.equal(c.S.load.kind,'custom');assert.equal(c.S.load.items.length,1);assert.equal(c.changeCount,1);
c.R=E.solve({geometry:{modules:1,customInteriorRibs:[],rodFractions:[]},assembly:{seamsBonded:true},load:{kind:'tip',tipForce:2}});
c.S.geometry=c.R.geometry;c.$('#app').dataset.lessonStage='shell';c.renderMemberLesson();
assert.match(c.$('#memberLesson').textContent,/No rods in this model/);
assert.ok(!/NaN|undefined|Infinity/.test(c.$('#memberLesson').innerHTML));
c.S.plot='model';
c.R={geometry:E.makeGeometry(),load:{kind:'custom',items:[{kind:'distributed',start:0,end:450,qStart:.01,qEnd:.01,fraction:.2},{kind:'distributed',start:0,end:450,qStart:-.01,qEnd:-.01,fraction:.7}]},props:{zBot:[0],zTop:[10]},point:[]};
c.model={loads:{children:[],add(a){this.children.push(a);}}};
c.sectionMotion=()=>[0];c.at=a=>a[0];c.COLORS={load:1,relief:2};
c.THREE={Vector3:class{constructor(x,y,z){Object.assign(this,{x,y,z});}},ArrowHelper:class{constructor(direction,origin,length,color){Object.assign(this,{direction,origin,length,color});}}};
vm.runInContext(source.slice(source.indexOf('  function drawLoads()'),source.indexOf('  function renderLegend(')),c);
c.drawLoads();
assert.equal(c.model.loads.children.length,26,'Opposite loads must not disappear when net transverse force cancels');
assert.equal(c.model.loads.children[0].origin.z,32);
assert.equal(c.model.loads.children[13].origin.z,112);
assert.equal(c.model.loads.children[0].direction.y,1);
assert.equal(c.model.loads.children[13].direction.y,-1);
wingDOM.window.close();
console.log('PASS: beam controls, supports, load forms, convergence table, graphics fallback, wing member lessons, separate stress controls, local strip scaling, custom wing load submission and force-couple arrow placement (DOM component tests; no WebGL rendering).');
